# Site settings
title: Lena Petrova
email: hello.lenapetrova@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dancer, model, performer, martial artist and teacher based in Berlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lenapetrova.com" # the base hostname & protocol for your site
instagram_username: lenapetrova__

# Build settings
markdown: kramdown
permalink: pretty
