# Site settings
title: Lena Petrova
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Dancer, performer, martial artist and model based in Berlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lenapetrova.com" # the base hostname & protocol for your site
instagram_username: lenapetrova__

# Build settings
markdown: kramdown
permalink: pretty
